In [3]:
import numpy as np
import pandas as pd
import sklearn

from sklearn.preprocessing import scale

In [5]:
pizza_data = np.array([[2100,   10,  800],
       [2500,   11,  850],
       [1800,   10,  760],
       [2000,   12,  800],
       [2300,   11,  810]])
scale(pizza_data)

array([[-0.16552118, -1.06904497, -0.1393466 ],
       [ 1.4896906 ,  0.26726124,  1.60248593],
       [-1.40693001, -1.06904497, -1.53281263],
       [-0.57932412,  1.60356745, -0.1393466 ],
       [ 0.66208471,  0.26726124,  0.2090199 ]])

In [8]:
scale(pizza_data).mean(axis=0).round(decimals=3)

array([ 0., -0.,  0.])

In [9]:
scale(pizza_data).std(axis=0).round(decimals=3)

array([1., 1., 1.])

In [10]:
from sklearn.preprocessing import MinMaxScaler

default_scaler = MinMaxScaler()

transformed = default_scaler.fit_transform(pizza_data)
print(transformed)

[[0.42857143 0.         0.44444444]
 [1.         0.5        1.        ]
 [0.         0.         0.        ]
 [0.28571429 1.         0.44444444]
 [0.71428571 0.5        0.55555556]]


In [13]:
default_scaler.min_

array([-2.57142857, -5.        , -8.44444444])

In [14]:
pizza_data

array([[2100,   10,  800],
       [2500,   11,  850],
       [1800,   10,  760],
       [2000,   12,  800],
       [2300,   11,  810]])